# Generated by Django 4.0.4 on 2022-04-30 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('local', models.CharField(max_length=80)),
                ('hora_inicio', models.IntegerField()),
                ('hora_termino', models.IntegerField()),
                ('observação', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
